# Generated by Django 4.2.7 on 2024-10-23 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 16, 19, 29, 755018, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 16, 19, 29, 755018, tzinfo=datetime.timezone.utc)),
        ),
    ]
