# Generated by Django 4.2.7 on 2024-10-23 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridul', '0003_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 16, 26, 41, 766261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 16, 26, 41, 766261, tzinfo=datetime.timezone.utc)),
        ),
    ]
